### ISSUE TITLE
Cannot resize Discord window from title bar (Windows)

### ISSUE THREAD

**Issue by h-anjru** [AryToNeX/Glasscord#39]
**Describe the bug**
Unable to resize the Discord window from the title bar. Resizing the window is still possible from the sides and bottom of the window. This applies both to vertical resizing and resizing from the top corners.

**To Reproduce**
1. Hover over the top edge of the Discord window.
2. The resize pointer does not appear, and the window cannot be resized from this position.

**Expected behavior**
When hovering over the top edge of the window, the resize pointer should appear and the click-and-drag-to-resize option should be available.

**Screenshots**
![image](https://user-images.githubusercontent.com/48505803/84215721-240e7e00-aa95-11ea-9e8a-e99690aaf156.png)
*Unable to resize window when hovering over edge*

**Desktop (please complete the following information):**
 - OS: Windows 10 64-bit (10.0.18363)
 - Discord version: 61327
 - Glasscord version: v0.2
 - Other Discord mods used: beautifuldiscord

**Additional context**
The `--glasscord-titlebar` settings which cause the resize functionality to break: `native`, `windows`, `osx`. The resize functionality works with setting `linux`, but this title bar appears on Windows as the default Windows title bar (see below).

![image](https://user-images.githubusercontent.com/48505803/84215797-73ed4500-aa95-11ea-8e19-d89b28e19d51.png)

**Comment by the-garlic-os** [comment]
Hello! I wrote a fix for this issue. The following CSS will let you resize the window from the title bar while covering up the thin opaque stripe at the top of the window.

Replace:
```css
.withFrame-haYltI {
	height: 18px;
	margin-top: 0;
	padding-top: 4px;
}
```
with:
```css
.withFrame-haYltI::after {
	content: "";
	width: 100%;
	height: 4px;
	background: var(--background-titlebar);
	position: absolute;
	left: 0; top: 0;
}
```
